
services:
  magicmirror:
    container_name: magicmirror-dev
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    shm_size: "1gb"
    ports:
      - "8080:8080"